name: Preview
on:
    workflow_call:
        secrets:
            githubAccessToken:
                required: true
        inputs:
            pipelineType:
                description: Pipeline Type
                default: build
                type: string
                required: false

env:
    uniqueWorkspaceId: /u/github/workspace/${{ github.repository }}/${{ github.ref_name }}/build_p${{github.run_number }} # adding a p to before the number,
    # to avoid an error caused by repeated build numbers 
    pipelineType: ${{ inputs.pipelineType }}
    branch : ${{ github.ref_name }} 
    application: ${{ github.event.repository.name }}
    packageName: ${{github.run_id}}
    zosHostname: lpar.dev.ibm.com
    zosSFTPUser: GITHUB@lpar.dev.ibm.com

jobs:
    Setup:
        runs-on: self-hosted
        steps:    
          - name: CI-CD pipeline parameter printout
            run: |
                echo " "
                echo "Following are the CI-CD pipeline parameters"
                echo "*******************************************"
                echo "uniqueWorkspaceId                  = ${{ env.uniqueWorkspaceId}}"
                echo "pipelineType                       = ${{ env.pipelineType}}"
                echo "branch                             = ${{ env.branch}}"
                echo "application                        = ${{ env.application}}"
                echo "packageName                        = ${{ env.packageName}}"
                echo "zosHostname                        = ${{ env.zosHostname}}"
                echo "zosSFTPUser                        = ${{ env.zosSFTPUser}}"
                
          - name: Clone Repo to z/OS Unix System Services
            run: ssh ${{env.zosSFTPUser}} ". ./.profile && gitClone.sh -w ${{ env.uniqueWorkspaceId }} -r https://${{ secrets.githubAccessToken }}@github.com/${{ github.repository }}.git -b ${{ env.branch }}" 

    Build:
        needs:
         - Setup
        runs-on: self-hosted
        steps: 
        - name: Build git repo
          # this makes use of zAppBuild, and the dbbBuild.sh common backend script 
          run: ssh ${{env.zosSFTPUser}} ". ./.profile && dbbBuild.sh -w ${{ env.uniqueWorkspaceId }} -a ${{env.application}} -b ${{ env.branch }} -p ${{env.pipelineType}}"
        
          # this makes use of zBuilder, and the zBuilder.sh common backend script
          # run: ssh ${{env.zosSFTPUser}} ". ./.profile && zBuilder.sh -w ${{ env.uniqueWorkspaceId }} -a ${{env.application}} -b ${{ env.branch }} -p ${{env.pipelineType}}"

        - name: Prepare logs
          if: ${{ always() }}
          run: |
              ssh ${{env.zosSFTPUser}} ". ./.profile && prepareLogs.sh -w ${{ env.uniqueWorkspaceId }}"  
              rm -rf "${{ runner.temp }}/build-logs" 
              mkdir "${{ runner.temp }}/build-logs" 
              sftp ${{env.zosSFTPUser}}:${{ env.uniqueWorkspaceId }}/*.tar "\"${{ runner.temp }}/build-logs\""
              tar -xvf "${{ runner.temp }}/build-logs/logs.tar" -C "${{ runner.temp }}/build-logs"
      
        - name: Upload build logs
          if: ${{ always() }}
          uses: actions/upload-artifact@v4
          with:
              name: build_${{github.run_number }}                        # Name used for artifact when it is uploaded
              path: ${{ runner.temp }}/build-logs                        # Path to build logs artifacts
              retention-days: 1